name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up environment variables
      run: echo "IMAGE_TAG=crostonj/techtwist-product:latest" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build ./Product --file ./Product/Dockerfile --tag ${{ env.IMAGE_TAG }}

    - name: Build and push image (ARM + AMD)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_PI_TAG}}
        platforms: linux/amd64,linux/arm64

    - name: Log in to Docker Hub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image for x86
      run: docker push ${{ env.IMAGE_TAG }}
    - name: Push the Docker image for Raspberry Pi 
      run: docker push ${{ env.IMAGE_PI_TAG }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Log out from Docker Hub
      run: docker logout
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

